version: '3'
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - './backend/.env.docker'
    ports:
      - "5432:5432"
    volumes:
      - './db/:/var/lib/postgresql/data'

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'api'
    env_file:
      - './backend/.env.docker'
    ports:
      - '3001:3001'
    depends_on:
      - postgres

  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: 'front'
    depends_on:
      - api

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - front
